apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::587344276961:role/UdacityFlaskDeployCBKubectlRole
    username: build
    groups:
      - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-04T06:39:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "20668"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: bf72980e-77cc-4498-9de5-149ff286a6c2
