apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::587344276961:role/UdacityFlaskDeployCBKubectlRole
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-04T04:34:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1507"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: eaf47393-5c98-4710-8e58-f6f5841b881f
