apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::587344276961:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-FXM66UD923HN
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::587344276961:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-04T19:17:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1701"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: fb2f8bd5-ef8b-4ed5-8a9f-63c861eb9a3e
