apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::587344276961:role/eksctl-simple-jwt-api-i-want-to-d-NodeInstanceRole-13OFODCKWQPH4
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
        - system:masters
      rolearn: arn:aws:iam::587344276961:role/UdacityFlaskDeployCBKubectlRole
      username: build
      
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-04T08:40:53Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "100707"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: e7e406fe-8947-4b78-81ab-777c68e59d6a
